### ISSUE TITLE
TS18003: No inputs were found in config file 'tsconfig.json'

### ISSUE THREAD

**Issue by VRuzhentsov** [sebastiandedeyne/laravel-mix-typescript-example#1]
Could you please take a look at my webpack config, and say in which way do i need to dig to resolve this error? 
https://pastebin.com/YvqCdvBt

error happens, when i provide `<script lang="ts">` in `.vue` component

**Comment by amitavroy** [comment]
Yes, even I am facing the same problem.

**Comment by sebastiandedeyne** [comment]
Laravel Mix 0.12+ supports TypeScript out of the box, I suggest using the `.typescript` function there instead of following the outdated instructions in this repo.
